### PR TITLE
Job DSL Examples for JTE

### PR DESCRIPTION
**Pull request by aleckeller**
Added a job DSL script for creating a organization jenkins job. Intended use is for people to add different job dsl scripts into this folder that they have created utilizing the JTE plugin.

### CODE REVIEW

**Comment by Vince-Cercury** [comment]
Does this solution only work for configuring a folder?

Is there an example available for only configuring a multibranch job?
The other pipeline in my folder are not JTE enabled yet.

My Job dsl uses multibranchPipelineJob function to create a job with github org

**Comment by Vince-Cercury** [comment]
So I made it work but the library section was not right. For reference


```
        it / 'projectFactories' << 'org.boozallen.plugins.jte.job.TemplateMultiBranchProjectFactory' {
        }
        it / factory(class: 'org.boozallen.plugins.jte.job.TemplateBranchProjectFactory') {
        }

        it / 'properties' << 'org.boozallen.plugins.jte.config.TemplateConfigFolderProperty' {
            tier {
                baseDir('configs/spark-bda')
                scm (class: 'hudson.plugins.git.GitSCM') {
                    configVersion 2
                    userRemoteConfigs {
                        'hudson.plugins.git.UserRemoteConfig' {
                            url orgPipelineRepo
                            credentialsId credId
                        }
                    }
                    branches{
                        'hudson.plugins.git.BranchSpec'{
                            name '*/master'
                        }
                    }
                }
                libraries{
                    'org.boozallen.plugins.jte.config.libraries.LibraryConfiguration'{
                        libraryProvider (class: 'org.boozallen.plugins.jte.config.libraries.ScmLibraryProvider'){
                            scm (class: 'hudson.plugins.git.GitSCM'){
                                configVersion 2
                                userRemoteConfigs{
                                    'hudson.plugins.git.UserRemoteConfig' {
                                        url libraryRepo
                                        credentialsId credId
                                    }
                                }
                                branches{
                                    'hudson.plugins.git.BranchSpec'{
                                        name '*/master'
                                    }
                                }
                            }
                            baseDir('libraries')
                        }
                    }
                }
            }
        }
```

**Comment by cokieffebah** [comment]
Thanks @Vince-Cercury.  we will have to add this DSL section to our documentation

**Comment by steven-terrana** [comment]
This issue if still applicable should be opened against the JenkinsCI repository.  closing this one as the original JTE is no longer maintained in favor of the official repository in the jenkinsci github organization

**Pull request closed without merging**
